import React from 'react';
import ControlCard from './ControlCard';
import Header from './Header';
import SettingsModal from './SettingsModal';
import './Documentation.css';

const arduinoCode = `/*
  Smart Space Control - ESP8266 Firmware
  Author: Generated by Antigravity
  
  Description:
  This code connects an ESP8266 to WiFi and polls a ThingSpeak channel for commands.
  It controls 8 outputs (Fans and Lights) based on Fields 1-8 of the ThingSpeak channel.
  
  Hardware:
  - ESP8266 NodeMCU (or similar)
  - 8-Channel Relay Module (Active LOW assumed)
  
  ThingSpeak Mapping:
  - Field 1 -> Fan 1 -> Pin D0 (GPIO 16)
  - Field 2 -> Fan 2 -> Pin D1 (GPIO 5)
  - Field 3 -> Fan 3 -> Pin D2 (GPIO 4)
  - Field 4 -> Fan 4 -> Pin D3 (GPIO 0)
  - Field 5 -> Light 1 -> Pin D4 (GPIO 2)
  - Field 6 -> Light 2 -> Pin D5 (GPIO 14)
  - Field 7 -> Light 3 -> Pin D6 (GPIO 12)
  - Field 8 -> Light 4 -> Pin D7 (GPIO 13)
*/

#include <ESP8266WiFi.h>
#include "ThingSpeak.h"

// --------------------------------------------------------------------------------
//  CONFIGURATION SECTION - EDIT THESE VALUES
// --------------------------------------------------------------------------------

// WiFi Credentials
const char* ssid = "YOUR_WIFI_SSID";
const char* password = "YOUR_WIFI_PASSWORD";

// ThingSpeak Channel Settings
// FOR SET 1: Use Channel 3250252
// FOR SET 2: Use Channel 3250257
unsigned long channelID = 3250252;        
const char* readAPIKey = "YZMUKLWR4D67NZZU";

// --------------------------------------------------------------------------------
//  PIN MAPPING
// --------------------------------------------------------------------------------

const int outputPins[8] = {D0, D1, D2, D3, D4, D5, D6, D7};

// Relay Configuration
const int RELAY_ON = LOW; // Active LOW
const int RELAY_OFF = HIGH;

WiFiClient client;
unsigned long lastTime = 0;
const unsigned long timerDelay = 3000; // Poll every 3 seconds

void setup() {
  Serial.begin(115200);
  
  // Initialize Pins
  for (int i = 0; i < 8; i++) {
    pinMode(outputPins[i], OUTPUT);
    digitalWrite(outputPins[i], RELAY_OFF);
  }

  // Connect to WiFi
  WiFi.mode(WIFI_STA);
  ThingSpeak.begin(client);
  
  connectWiFi();
}

void loop() {
  if (WiFi.status() != WL_CONNECTED) {
    connectWiFi();
  }

  if ((millis() - lastTime) > timerDelay) {
    readThingSpeak();
    lastTime = millis();
  }
}

void connectWiFi() {
  Serial.print("Connecting to WiFi: ");
  Serial.println(ssid);
  WiFi.begin(ssid, password);
  
  int timeout = 0;
  while (WiFi.status() != WL_CONNECTED && timeout < 20) {
    delay(500);
    Serial.print(".");
    timeout++;
  }
  
  if (WiFi.status() == WL_CONNECTED) {
    Serial.println("\\nWiFi Connected.");
    Serial.print("IP Address: ");
    Serial.println(WiFi.localIP());
  } else {
    Serial.println("\\nWiFi Connection Failed. Retrying...");
  }
}

void readThingSpeak() {
  Serial.println("\\nReading from ThingSpeak...");
  
  int statusCode = ThingSpeak.readMultipleFields(channelID, readAPIKey);
  
  if (statusCode == 200) {
    Serial.println("Data received.");
    
    for (int i = 1; i <= 8; i++) {
      int value = ThingSpeak.getFieldAsInt(i);
      if (value == 1) {
        digitalWrite(outputPins[i-1], RELAY_ON);
        Serial.printf("Field %d: ON\\n", i);
      } else {
        digitalWrite(outputPins[i-1], RELAY_OFF);
        Serial.printf("Field %d: OFF\\n", i);
      }
    }
  } else {
    Serial.printf("Error reading: %d\\n", statusCode);
  }
}
`;

const Dashboard = () => {
    // Default configuration
    const defaultSets = [
        {
            title: "SMART SPACE – SET 1",
            channelId: "3250252",
            readKey: "YZMUKLWR4D67NZZU",
            writeKey: "5Q6OYJ7R6W2H30HF"
        },
        {
            title: "SMART SPACE – SET 2",
            channelId: "3250257",
            readKey: "CFXKSK8INWTHAGN1",
            writeKey: "6Q6EFKF92SNIEGHX"
        }
    ];

    const [sets, setSets] = React.useState(() => {
        const saved = localStorage.getItem('smartSpaceConfig');
        return saved ? JSON.parse(saved) : defaultSets;
    });

    const [isSettingsOpen, setIsSettingsOpen] = React.useState(false);

    const handleSaveSettings = (newConfig) => {
        setSets(newConfig);
        localStorage.setItem('smartSpaceConfig', JSON.stringify(newConfig));
    };

    const [currentView, setCurrentView] = React.useState('home');

    const handleNavigate = (view) => {
        if (view === 'home') {
            setCurrentView('home');
        } else if (view === 'docs') {
            setCurrentView('docs');
        }
    };

    return (
        <div className="dashboard-container">
            <Header onOpenSettings={() => setIsSettingsOpen(true)} onNavigate={handleNavigate} />

            {currentView === 'home' && (
                <div className="cards-wrapper">
                    {sets.map((set, index) => (
                        <ControlCard
                            key={`${index}-${set.channelId}`} // Re-mount if channel changes
                            {...set}
                        />
                    ))}
                </div>
            )}

            {currentView === 'docs' && (
                <div className="glass-panel docs-container">
                    <h1>Documentation</h1>
                    <div className="docs-content">
                        <h2>1. Dashboard Setup</h2>
                        <p>This dashboard is pre-configured for Mahendra Engineering College Smart Space. To ensure proper operation:</p>
                        <ul>
                            <li>Ensure you are connected to the internet.</li>
                            <li>The dashboard polls ThingSpeak every 3 seconds.</li>
                            <li>If a control automatically turns off, it means the command is being sent, but the ESP8266 hasn't updated the status field yet.</li>
                        </ul>

                        <h2>2. Settings Configuration</h2>
                        <p>Click the <b>Settings</b> button in the header to configure Channel IDs and API Keys.</p>
                        <ul>
                            <li><b>Set 1:</b> Channel 3250252 (Default)</li>
                            <li><b>Set 2:</b> Channel 3250257 (Default)</li>
                        </ul>

                        <h2>3. Hardware Logic</h2>
                        <p>The system controls 8 devices per set:</p>
                        <ul>
                            <li><b>Fans 1-4:</b> Mapped to Fields 1-4</li>
                            <li><b>Lights 1-4:</b> Mapped to Fields 5-8</li>
                        </ul>

                        <h2>4. ESP8266 Firmware (8+8 Setup)</h2>
                        <p>To control 16 devices, you need <b>TWO separate ESP8266 boards</b>.</p>
                        <ul className="setup-list">
                            <li><b>Board 1 (Set 1):</b> Use Channel ID <code className="highlight">3250252</code></li>
                            <li><b>Board 2 (Set 2):</b> Use Channel ID <code className="highlight">3250257</code></li>
                        </ul>
                        <div className="code-header">
                            <p>Upload this code to both boards (change Channel ID for Board 2):</p>
                            <button className="copy-btn" onClick={() => {
                                navigator.clipboard.writeText(arduinoCode);
                                alert('Code copied to clipboard!');
                            }}>Copy Code</button>
                        </div>
                        <div className="code-block-wrapper">
                            <pre className="code-block"><code>{arduinoCode}</code></pre>
                        </div>
                    </div>
                </div>
            )}

            <SettingsModal
                isOpen={isSettingsOpen}
                onClose={() => setIsSettingsOpen(false)}
                channelConfig={sets}
                onSave={handleSaveSettings}
            />
        </div>
    );
};

export default Dashboard;
